apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: muenster-jetzt

resources:
- namespace.yaml
- backend-secret.yaml
- ../base

images:
- name: docker.io/codeformuenster/muenster-jetzt-frontend
  newTag: pr-772@sha256:1e5961eee872bf08c77a8ce224dfa693a69778cde9a412f0490c03db56aa0fab
- name: docker.io/codeformuenster/muenster-jetzt-api
  newTag: pr-772@sha256:804e34a6c9ce116de9e2bc4c773fa6ea3d4ad6963ccba09a83fb94e9700c9cda
- name: docker.io/codeformuenster/muenster-jetzt-api-static
  newTag: pr-772@sha256:c7c98f00d6e1a9359544db2bbaf274ea3e04f69e76177aa7edb470df16c165fb

patches:
- patch: |
    - op: add
      path: /spec/ingressClassName
      value: traefik
  target:
    kind: Ingress
- patch: |
    - op: add
      path: /spec/rules/0/host
      value: api.dev.muenster-jetzt.codeformuenster.org
  target:
    kind: Ingress
    name: backend
- patch: |
    - op: add
      path: /spec/rules/0/host
      value: dev.muenster-jetzt.codeformuenster.org
  target:
    kind: Ingress
    name: frontend
- patch: |
    - op: add
      path: /spec/template/metadata/labels/host
      value: api.dev.muenster-jetzt.codeformuenster.org
  target:
    kind: Deployment
    name: backend-api
