# Generated by Django 3.1.2 on 2020-11-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formatted_description',
            field=models.TextField(blank=True, help_text='HTML event description and details (if available from source, otherwise matches plain text description). Will only contain these HTML tags: b, br, em, i, li, p, span, strong, ul.', null=True),
        ),
    ]
