# Generated by Django 3.1.2 on 2020-11-04 15:38

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20201104_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="dirty_fields",
            field=events.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("source_url", "source_url"),
                        ("source_license", "source_license"),
                        ("name", "name"),
                        ("description", "description"),
                        ("formatted_description", "formatted_description"),
                        ("url", "url"),
                        ("start_date", "start_date"),
                        ("start_time", "start_time"),
                        ("end_date", "end_date"),
                        ("end_time", "end_time"),
                        ("location", "location"),
                        ("performer", "performer"),
                        ("mode", "mode"),
                        ("organizer", "organizer"),
                    ],
                    max_length=63,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
