apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-static
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-static
    spec:
      serviceAccountName: backend-static
      containers:
      - image: docker.io/codeformuenster/muenster-jetzt-api-static:master
        name: backend-static
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 101
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8001
          name: http
        volumeMounts:
        - name: tmpdir
          mountPath: /tmp
      volumes:
      - name: tmpdir
        emptyDir:
          medium: Memory
