apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-static
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    spec:
      containers:
      - image: codeformuenster/muenster-jetzt-api-static:master
        name: backend-static
        resources: {}
        ports:
        - containerPort: 8001
          name: http
