version: 2

updates:
  # frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "component/frontend"
    registries:
      - dockerhub
  # github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    registries:
      - dockerhub
  # backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "component/backend"
    registries:
      - dockerhub
  # infrastructure
  - package-ecosystem: "docker"
    directory: "/infrastructure/https_proxy/files/"
    schedule:
      interval: "monthly"
    reviewers:
      - "bCyberBasti"
    labels:
      - "dependencies"
      - "deployment"
    registries:
      - dockerhub

registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{ secrets.DOCKER_HUB_USER }}
    password: ${{ secrets.DOCKER_HUB_PASS }}
