version: 2

updates:
  # frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "component/frontend"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
