version: 2

updates:
  # frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "component/frontend"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # infrastructure
  - package-ecosystem: "docker"
    directory: "/infrastructure/https_proxy/files/"
    schedule:
      interval: "daily"
    reviewers:
      - "bCyberBasti"
    labels:
      - "dependencies"
      - "deployment"
