---
- name: set timezone to {{ tz }}
  timezone:
    name: "{{ tz }}"

- name: Change locale to EN
  command: update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

- name: Set hostname on server
  hostname: 
    name: "{{ hostname }}"
  when: hostname is defined

- apt:
    name: htop
    state: present
    update_cache: yes
