- name: Add Docker key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
- name: Add Docker apt repo
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: true

- name: install docker and dependencies
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
    state: present

- name: python docker / docker-compse module
  pip:
    name:
      - docker-compose