apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    spec:
      containers:
      - image: postgis/postgis:14
        name: postgis
        resources: {}
        # See for options: https://registry.hub.docker.com/_/postgres/
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres
              key: name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        ports:
        - containerPort: 3306
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
