FROM alpine:3.12 AS compress

RUN apk --no-cache add gzip findutils

COPY build /www

RUN find /www \
  -type f -regextype posix-extended \
  -size +512c \
  -iregex '.*\.(css|html?|js|svg|txt|json)' \
  -exec gzip -9 -k '{}' \;

FROM nginxinc/nginx-unprivileged:1.18-alpine

COPY --chown=101 deployment/muenster-jetzt.nginx.conf /etc/nginx/conf.d/default.conf

COPY --chown=101 --from=compress /www /www
