apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    spec:
      containers:
      - image: codeformuenster/muenster-jetzt-frontend:master
        name: postgis
        resources: {}
        ports:
        - containerPort: 8080
          name: http

    # volumes:
    #   - "../uploads:/www/static/uploads:ro"
