[providers.docker]
  endpoint = "tcp://socket-proxy:2375"
  exposedByDefault = false
  
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

[certificatesResolvers.letsencrypt.acme]
  email = "basti@bcyber.de"
  storage = "/letsencrypt/acme.json"
  httpchallenge = true
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"