apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: frontend

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- ingress.yaml
