---
- name: install apt packages
  apt:
    name: ['unattended-upgrades', 'apticron']
    state: present
    
- name: copy unattended-upgrades config
  copy:
    src: files/10periodic
    dest: /etc/apt/apt.conf.d/10periodic
  