FROM python:3.8

WORKDIR /app

ENV PYTHONFAULTHANDLER=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY mj mj
COPY migrations migrations
COPY setup.py .

RUN pip install .

ENTRYPOINT ["python", "-m", "mj"]

CMD ["serve", "--host", "0.0.0.0"]
