---
- name: create uploads dir
  file:
    path: /root/muenster-jetzt/uploads/static
    state: directory

- name: create staging dir
  file:
    path: /root/muenster-jetzt/staging
    state: directory

- name: Copy staging .env
  template:
    src: files/env-staging.j2
    dest: /root/muenster-jetzt/staging/.env
    owner: root
    group: root

- name: create production dir
  file:
    path: /root/muenster-jetzt/production
    state: directory