name: backend-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: backend

jobs:
  backend:
    name: Build backend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2' # for comparison

      - name: Determine if job is required
        id: git-diff
        continue-on-error: true
        run: |
          echo "##[set-output name=changes;]$(git diff --name-only HEAD^1 -- . | wc -l)"

      - name: Extract branch name and shortened commit sha
        if: steps.git-diff.outputs.changes != '0'
        id: extract_branch
        run: |
          echo "##[set-output name=branch_name;]${GITHUB_REF##*/}"
          echo "##[set-output name=short_sha;]${GITHUB_SHA:0:7}"

      - name: Build Image and Push to Docker Hub
        if: github.event_name == 'push' && steps.extract_branch.outputs.branch_name == 'master' && steps.git-diff.outputs.changes != '0'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.FRONTEND_DOCKER_HUB_USER }}
          password: ${{ secrets.FRONTEND_DOCKER_HUB_PASS }}
          repository: codeformuenster/muenster-jetzt-api
          dockerfile: backend/deployment/Dockerfile.prod
          tags: ${{ steps.extract_branch.outputs.branch_name }},${{ steps.extract_branch.outputs.branch_name }}-${{ steps.extract_branch.outputs.short_sha }}
          path: backend
          tag_with_ref: true
