name: frontend-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: frontend

jobs:
  check-api-client-up-to-date:
    name: Check if generated api client is up to date
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2' # for comparison

      - name: Determine if job is required
        id: git-diff
        continue-on-error: true
        run: |
          echo "##[set-output name=changes;]$(git diff --name-only HEAD^1 -- . | wc -l)"

      - name: Install Node.js 14
        if: steps.git-diff.outputs.changes != '0'
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14

      - name: Cache node modules
        if: steps.git-diff.outputs.changes != '0'
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run 'npm ci' to install frontend dependencies
        if: steps.git-diff.outputs.changes != '0'
        run: |
          npm ci

      - name: Build backend image
        if: steps.git-diff.outputs.changes != '0'
        uses: docker/build-push-action@v1
        with:
          push: false
          repository: muenster-jetzt-api
          dockerfile: backend/Dockerfile # TODO change this once 77 is in master
          tags: in-ci
          path: backend

      - name: Start container from backend image
        if: steps.git-diff.outputs.changes != '0'
        run: |
          docker run --rm -d --name backend muenster-jetzt-api:in-ci serve
          sleep 3
          docker exec -t backend curl localhost:8000/openapi.json > api-client/spec.json

      - name: Run 'npm run generate-client'
        if: steps.git-diff.outputs.changes != '0'
        run: |
          npm run generate-client

      - name: Check for changes according to git
        if: steps.git-diff.outputs.changes != '0'
        run: |
          git diff-index --exit-code -p HEAD

  frontend:
    name: Validate, test and build frontend
    runs-on: ubuntu-18.04
    needs: check-api-client-up-to-date
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2' # for comparison

      - name: Determine if job is required
        id: git-diff
        continue-on-error: true
        run: |
          echo "##[set-output name=changes;]$(git diff --name-only HEAD^1 -- . | wc -l)"

      - name: Debug
        run: |
          echo "Number of changed files in frontend directory: '${{ steps.git-diff.outputs.changes }}'"

      - name: Install Node.js 14
        if: steps.git-diff.outputs.changes != '0'
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14

      - name: Cache node modules
        if: steps.git-diff.outputs.changes != '0'
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run 'npm ci' to install frontend dependencies
        if: steps.git-diff.outputs.changes != '0'
        run: |
          npm ci

      - name: Check frontend code style
        if: steps.git-diff.outputs.changes != '0'
        run: |
          npm run lint

      - name: Run frontend tests
        if: steps.git-diff.outputs.changes != '0'
        run: |
          npm run test

      - name: Extract branch name, shortened commit sha and build env variables
        if: steps.git-diff.outputs.changes != '0'
        id: extract_branch
        run: |
          branch_name=${GITHUB_REF##*/}
          short_sha=${GITHUB_SHA:0:7}

          echo "##[set-output name=branch_name;]${branch_name}"
          echo "##[set-output name=short_sha;]${short_sha}"
          echo "##[set-env name=REACT_APP_VERSION;]${branch_name}-${short_sha}"
          if [ "$branch_name" = "production" ]; then
            echo "##[set-env name=REACT_APP_BACKEND_BASE_PATH;]https://api.muenster-jetzt.de"
          else
            echo "##[set-env name=REACT_APP_BACKEND_BASE_PATH;]https://api.staging.muenster-jetzt.de"
          fi

      - name: Build frontend
        if: steps.git-diff.outputs.changes != '0'
        run: |
          echo "Executing npm run build with env REACT_APP_VERSION='$REACT_APP_VERSION' and REACT_APP_BACKEND_BASE_PATH='$REACT_APP_BACKEND_BASE_PATH'"
          npm run build

      - name: Build Image and Push to Docker Hub
        if: github.event_name == 'push' && steps.extract_branch.outputs.branch_name == 'master' && steps.git-diff.outputs.changes != '0'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.FRONTEND_DOCKER_HUB_USER }}
          password: ${{ secrets.FRONTEND_DOCKER_HUB_PASS }}
          repository: codeformuenster/muenster-jetzt-frontend
          dockerfile: frontend/deployment/Dockerfile.prod
          tags: ${{ steps.extract_branch.outputs.branch_name }},${{ steps.extract_branch.outputs.branch_name }}-${{ steps.extract_branch.outputs.short_sha }}
          path: frontend
          tag_with_ref: true

  deploy:
    name: deploy to server
    runs-on: ubuntu-18.04
    needs: frontend
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "##[set-output name=branch_name;]${GITHUB_REF##*/}"

      - name: Copy docker-compose file to server
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
            # z = compress
            # v = verbose
            ARGS: "-zv"
            SOURCE: deployment/docker-compose.yml
            REMOTE_HOST: "staging.muenster-jetzt.de"
            REMOTE_USER: root
            TARGET: "/root/muenster-jetzt/staging/"

      - name: Run remote commands
        uses: appleboy/ssh-action@master
        with:
          host: "staging.muenster-jetzt.de"
          username: root
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script_stop: true
          script: |
            set -e
            cd muenster-jetzt/staging
            docker-compose pull
            docker-compose up --detach --remove-orphans
            docker image prune --all --force
