name: frontend-ci

on:
  push:
    branches:
      - master
      - staging
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - master
      - staging
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  frontend:
    name: Validate, test and build frontend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run 'npm ci' to install frontend dependencies
        run: |
          npm ci

      - name: Check frontend code style
        run: |
          npm run lint

      - name: Run frontend tests
        run: |
          npm run test

      - name: Build frontend
        run: |
          npm run build

      - name: Build Image and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.FRONTEND_DOCKER_HUB_USER }}
          password: ${{ secrets.FRONTEND_DOCKER_HUB_PASS }}
          repository: codeformuenster/muenster-jetzt-frontend
          dockerfile: frontend/deployment/Dockerfile.prod
          path: frontend
          tags: latest
          tag_with_ref: true
