name: Check kubernetes manifests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Lint kubernetes manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and validate kustomizations
        uses: ubergesundheit/kube-check-action@main
        with:
          kustomize_build_input: deployment/base
          kubeconform_flags: "-strict -kubernetes-version 1.25.8 -schema-location 'https://raw.githubusercontent.com/ubergesundheit/kube-check-action/main/kubeconform-schemas/{{.ResourceKind}}.json' -schema-location default"
          kube-linter_flags: "--config deployment/base/.kube-linter.yaml"
