name: periodic import

on:
  schedule:
    # run every hour
    - cron: '0 * * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  production:
    name: crawl events in production
    runs-on: ubuntu-22.04
    steps:
      - name: PRODUCTION  Run remote commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: "muenster-jetzt.de"
          username: root
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script_stop: true
          script: |
            set -e
            cd muenster-jetzt/production
            docker-compose exec -T api ./manage.py crawl
